### ISSUE TITLE
About identification, authentication and authorization

### ISSUE THREAD

**Issue by qligier** [teesloane/Auth-Boss#5] opened 2017-02-24 14:48 UTC
Hey,

I think there's a bit of confusion between identification, authentication and authorization and it could be good to clear that. [This](https://danielmiessler.com/blog/security-identification-authentication-and-authorization/) could help to define the three terms.

The principal issue is the description of OAuth2: it's about authorization, not authentication (as is OpenID and the other methods). Facebook, Google and others keep their own identification/authentication system and, as a user, you still have to authenticate yourself to them. OAuth2 will then authorize (as you've requested) the other site to use some of your data (email address, name, maybe more; it could be defined in the scope). To do so, it must identify you to the site (so you could indeed use it as an identification protocol) but it's not why it has been designed. [This StackOverflow topic](http://stackoverflow.com/questions/33702826/oauth-authorization-vs-authentication) surely explains it better.

It could also be dangerous to use OAuth2 as an identification protocol (even if Google and Facebook use it that way). [This answer on StackExchange](http://security.stackexchange.com/a/119252) and the [OAuth2 RFC](https://tools.ietf.org/html/rfc6749#section-10.16) explain why.

Weirdly, the Authorization header is about authentication (I don't understand the name choice).

Good job, though :+1: 
Quentin

**Comment by qligier** [comment] 2017-02-24 14:50
Duplicate of #4, I've been quite slow to write that :smiley:

**Comment by teesloane** [comment] 2017-02-27 00:52
Closing as this is a duplicate of #4

**Closed by teesloane** 2017-02-27 00:52 UTC
